# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 1.4
  - nightly
notifications:
  email: false
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true

## uncomment the following lines to override the default test script
script:
 - travis_wait 50 julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test()'
